theme = "nord"

[editor]
line-number = "relative"
idle-timeout = 50
completion-timeout = 50
auto-format = true

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = [ "position", "position-percentage", "file-type"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.indent-guides]
render = true
character = "╎"

[editor.search]
smart-case = false

[editor.whitespace.render]
newline = "all"

# [editor.lsp]
# display-inlay-hints = true

[editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
newline = "⏎"
