theme = "nightfox"

[editor]
line-number = "relative"
idle-timeout = 50
completion-timeout = 50
auto-format = true
middle-click-paste = false
insert-final-newline = false
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [ "position","primary-selection-length","total-line-numbers", "position-percentage", "file-type"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.indent-guides]
render = true
character = "╎"

[editor.search]
smart-case = false

[editor.whitespace.render]
newline = "all"

# [editor.lsp]
# display-inlay-hints = true

[editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
newline = "⏎"


[editor.inline-diagnostics]
cursor-line = "warning"
